import { existsSync } from "node:fs";
import { mkdir, readFile, readdir, rm, writeFile } from "node:fs/promises";
import path from "node:path";

const ROOT = path.resolve(import.meta.dirname, "..");
const SYMBOLS = path.join(ROOT, "node_modules/@material-symbols/svg-400");
const FIGMA = path.join(ROOT, ".claude/figma/assets");
const OUT = path.join(ROOT, "src/components/icons");

const symbols = [
  ["Search", "outlined", "search"],
  ["ShoppingBag", "outlined", "shopping_bag"],
  ["StarRate", "rounded", "star_rate", true],
  ["Star", "rounded", "star", true],
  ["SignalCellularAlt", "outlined", "signal_cellular_alt"],
  ["CheckCircle", "outlined", "check_circle", true],
  ["FilterAlt", "outlined", "filter_alt"],
  ["Category", "outlined", "category"],
  ["Sort", "outlined", "sort"],
  ["ChevronLeft", "outlined", "chevron_left"],
  ["ChevronRight", "outlined", "chevron_right"],
  ["KeyboardArrowDown", "outlined", "keyboard_arrow_down"],
  ["Share", "outlined", "share"],
  ["PlayArrow", "outlined", "play_arrow", true],
  ["Videocam", "outlined", "videocam"],
  ["Group", "outlined", "group"],
  ["Topic", "outlined", "topic"],
  ["Badge", "outlined", "badge"],
  ["Computer", "outlined", "computer"],
  ["Domain", "rounded", "domain"],
  ["ConnectWithoutContact", "outlined", "connect_without_contact"],
  ["PhotoCameraFront", "outlined", "photo_camera_front"],
  ["Menu", "outlined", "menu"],
  ["Close", "outlined", "close"],
];

const custom = [
  ["DeveloperMode", "icons/developer-mode.svg", true],
  ["Design", "manual/icon-design.svg", true, ["outlined", "design_services"]],
  ["Facebook", "manual/icon-facebook.svg", false, "facebook.svg"],
  ["Google", "manual/icon-google.svg", false, "google.svg"],
];

const header = (source) =>
  `// Generated by scripts/build-icons.mjs from ${source}. Do not edit; re-run \`npm run icons\`.\n`;

const component = (
  name,
  source,
  viewBox,
  body,
) => `${header(source)}import type { IconProps } from "./types";

export function ${name}Icon({ size = 24, ...props }: IconProps) {
  return (
    <svg viewBox="${viewBox}" width={size} height={size} fill="currentColor" aria-hidden {...props}>
      ${body}
    </svg>
  );
}
`;

const camel = (attr) => attr.replace(/-([a-z])/g, (_, c) => c.toUpperCase());

function toJsx(markup, mono) {
  const referenced = new Set(
    [...markup.matchAll(/url\(#([^)]+)\)/g)].map((m) => m[1]),
  );
  let jsx = markup
    .replace(/\s+id="([^"]*)"/g, (m, id) => (referenced.has(id) ? m : ""))
    .replace(/\s([a-z]+(?:-[a-z]+)+)=/g, (_, attr) => ` ${camel(attr)}=`)
    .replace(/\s+style="[^"]*"/g, "")
    .replace(/>\s+</g, "><")
    .trim();
  if (mono) jsx = jsx.replace(/fill="(?!none)[^"]*"/g, 'fill="currentColor"');
  return jsx;
}

async function readSvg(file) {
  const svg = await readFile(file, "utf8");
  const viewBox = svg.match(/viewBox="([^"]+)"/)?.[1];
  const inner = svg.match(/<svg[^>]*>([\s\S]*)<\/svg>/)?.[1];
  if (!viewBox || inner === undefined) throw new Error(`Can't parse ${file}`);
  return { viewBox, inner };
}

async function symbol(style, glyph, filled) {
  const rel = `${style}/${glyph}${filled ? "-fill" : ""}.svg`;
  const { viewBox, inner } = await readSvg(path.join(SYMBOLS, rel));
  return {
    source: `@material-symbols/svg-400/${rel}`,
    viewBox,
    body: toJsx(inner, true),
  };
}

async function main() {
  if (!existsSync(SYMBOLS))
    throw new Error("Run `npm i -D @material-symbols/svg-400` first.");
  await mkdir(OUT, { recursive: true });
  for (const file of await readdir(OUT)) {
    if (file.endsWith("Icon.tsx")) await rm(path.join(OUT, file));
  }

  const names = [];
  const warnings = [];

  for (const [name, style, glyph, filled] of symbols) {
    const { source, viewBox, body } = await symbol(style, glyph, filled);
    await writeFile(
      path.join(OUT, `${name}Icon.tsx`),
      component(name, source, viewBox, body),
    );
    names.push(name);
  }

  for (const [name, rel, mono, fallback] of custom) {
    const file = path.join(FIGMA, rel);
    let icon;
    if (existsSync(file)) {
      const { viewBox, inner } = await readSvg(file);
      icon = {
        source: `.claude/figma/assets/${rel}`,
        viewBox,
        body: toJsx(inner, mono),
      };
    } else if (typeof fallback === "string") {
      const { viewBox, inner } = await readSvg(
        path.join(ROOT, "scripts/icon-fallbacks", fallback),
      );
      icon = {
        source: `scripts/icon-fallbacks/${fallback}`,
        viewBox,
        body: toJsx(inner, true),
      };
      warnings.push(
        `${rel} is missing; ${name}Icon uses the ${fallback} stand-in until the manual export lands`,
      );
    } else if (fallback) {
      icon = await symbol(...fallback);
      warnings.push(
        `${rel} is missing; ${name}Icon uses ${fallback[1]} until the manual export lands`,
      );
    } else {
      warnings.push(`${rel} is missing; ${name}Icon was not generated`);
      continue;
    }
    await writeFile(
      path.join(OUT, `${name}Icon.tsx`),
      component(name, icon.source, icon.viewBox, icon.body),
    );
    names.push(name);
  }

  await writeFile(
    path.join(OUT, "types.ts"),
    `${header("its own template")}import type { SVGProps } from "react";

export type IconProps = Omit<SVGProps<SVGSVGElement>, "children"> & {
  /** Rendered width and height (px number or any CSS length). */
  size?: number | string;
};
`,
  );
  await writeFile(
    path.join(OUT, "index.ts"),
    `${header("the icon list")}export type { IconProps } from "./types";\n` +
      names
        .sort()
        .map((n) => `export { ${n}Icon } from "./${n}Icon";`)
        .join("\n") +
      "\n",
  );

  console.log(`Wrote ${names.length} icons to ${path.relative(ROOT, OUT)}`);
  for (const w of warnings) console.warn(`  ! ${w}`);
}

await main();
