// Generated by scripts/build-icons.mjs from @material-symbols/svg-400/outlined/close.svg. Do not edit; re-run `npm run icons`.
import type { IconProps } from "./types";

export function CloseIcon({ size = 24, ...props }: IconProps) {
  return (
    <svg viewBox="0 -960 960 960" width={size} height={size} fill="currentColor" aria-hidden {...props}>
      <path d="m249-207-42-42 231-231-231-231 42-42 231 231 231-231 42 42-231 231 231 231-42 42-231-231-231 231Z"/>
    </svg>
  );
}
