// Generated by scripts/build-icons.mjs from @material-symbols/svg-400/outlined/computer.svg. Do not edit; re-run `npm run icons`.
import type { IconProps } from "./types";

export function ComputerIcon({ size = 24, ...props }: IconProps) {
  return (
    <svg viewBox="0 -960 960 960" width={size} height={size} fill="currentColor" aria-hidden {...props}>
      <path d="M40-120v-60h880v60H40Zm100-120q-24 0-42-18t-18-42v-480q0-24 18-42t42-18h680q24 0 42 18t18 42v480q0 24-18 42t-42 18H140Zm0-60h680v-480H140v480Zm0 0v-480 480Z"/>
    </svg>
  );
}
