// Generated by scripts/build-icons.mjs from @material-symbols/svg-400/outlined/menu.svg. Do not edit; re-run `npm run icons`.
import type { IconProps } from "./types";

export function MenuIcon({ size = 24, ...props }: IconProps) {
  return (
    <svg viewBox="0 -960 960 960" width={size} height={size} fill="currentColor" aria-hidden {...props}>
      <path d="M120-240v-60h720v60H120Zm0-210v-60h720v60H120Zm0-210v-60h720v60H120Z"/>
    </svg>
  );
}
