// Generated by scripts/build-icons.mjs from its own template. Do not edit; re-run `npm run icons`.
import type { SVGProps } from "react";

export type IconProps = Omit<SVGProps<SVGSVGElement>, "children"> & {
  /** Rendered width and height (px number or any CSS length). */
  size?: number | string;
};
